export const DOWNLOAD_USERS = 'DOWNLOAD_USERS',
             DOWNLOAD_USERS_SUCCESS = 'DOWNLOAD_USERS_SUCCESS',
             DOWNLOAD_USERS_ERROR = 'DOWNLOAD_USERS_ERROR',

             DOWNLOAD_USERNAME = 'DOWNLOAD_USERNAME',
             DOWNLOAD_USERNAME_SUCCESS = 'DOWNLOAD_USERNAME_SUCCESS',
             DOWNLOAD_USERNAME_ERROR = 'DOWNLOAD_USERNAME_ERROR',

             DOWNLOAD_USER_GAMES = 'DOWNLOAD_USER_GAMES',
             DOWNLOAD_USER_GAMES_SUCCESS = 'DOWNLOAD_USER_GAMES_SUCCESS',
             DOWNLOAD_USER_GAMES_ERROR = 'DOWNLOAD_USER_GAMES_ERROR',

             DOWNLOAD_GAMES = 'DOWNLOAD_GAMES',
             DOWNLOAD_GAMES_SUCCESS = 'DOWNLOAD_GAMES_SUCCESS',
             DOWNLOAD_GAMES_ERROR = 'DOWNLOAD_GAMES_ERROR',

             CREATE_NEW_GAME = 'CREATE_NEW_GAME',
             NEW_GAME_SUCCESS = 'NEW_GAME_SUCCESS',
             NEW_GAME_ERROR = 'NEW_GAME_ERROR',

             DOWNLOAD_TEAMS = 'DOWNLOAD_TEAMS',
             DOWNLOAD_TEAMS_SUCCESS = 'DOWNLOAD_TEAMS_SUCCESS',
             DOWNLOAD_TEAMS_ERROR = 'DOWNLOAD_TEAMS_ERROR',

             DOWNLOAD_DIFFERENCE = 'DOWNLOAD_DIFFERENCE',
             DOWNLOAD_DIFFERENCE_SUCCESS = 'DOWNLOAD_DIFFERENCE_SUCCESS',
             DOWNLOAD_DIFFERENCE_ERROR = 'DOWNLOAD_DIFFERENCE_ERROR';